fix(data): removed scrapping, get data from raw json
devschile/huemul pull request #657
Opened 2021-01-24 19:56 UTC by juanbrujo

removed scrapping from La Segunda (buggy), now script reads directly from static JSON: https://gist.github.com/juanbrujo/c27f9bea0f5a7ac56802122ec50d5a9b

test: `huemul santoral`
> Hoy *domingo 24 de enero* el santoral es *Francisco de Sales* :angel:

2021-01-25 14:22 UTC, juanbrujo commented
hola alguien puede revisar este PR? saludos cordiales.

2021-01-25 14:27 UTC, gmq commented on scripts/santoral.js
> +        Object.keys(santoral).map(function(key) {
Funcionará un if tipo

```javascript
if (santoral[currentMonth]) {
```

en vez de recorrer el objeto? O llamar directo el objeto, considerando que todos los meses están en el archivo

2021-01-25 14:49 UTC, lgaticaq requested changes

2021-01-25 14:49 UTC, lgaticaq commented on scripts/santoral.js
> +const weekDay = moment().format('dddd')
**sugerencia**: creo que esto debe ir dentro del module exports ya que es el código que reside allí el que se ejecuta en cada llamada al comando

2021-01-25 14:49 UTC, lgaticaq commented on scripts/santoral.js
> +      if (response.statusCode !== 200 || !error) {
**pregunta**: esto debiese ser `response.statusCode === 200` o no?

2021-01-25 14:49 UTC, lgaticaq commented on scripts/santoral.js
> +        Object.keys(santoral).map(function(key) {
coincido con el comentario de @gmq

2021-01-25 15:03 UTC, juanbrujo commented on scripts/santoral.js
> +      if (response.statusCode !== 200 || !error) {
es raro eso porque me daba error con lo que propones, lo volveré a probar

2021-01-25 15:03 UTC, juanbrujo commented on scripts/santoral.js
> +const weekDay = moment().format('dddd')
ok

2021-01-25 15:03 UTC, juanbrujo commented on scripts/santoral.js
> +        Object.keys(santoral).map(function(key) {
me late chocolate

2021-01-25 16:03 UTC, juanbrujo commented
@gmq @lgaticaq listo mejoras sugeridas

2021-01-26 12:03 UTC, juanbrujo commented
@gmq @lgaticaq 👍 👎 ❓

2021-01-27 12:20 UTC, juanbrujo commented
alo, alguien? @gmq ? @hectorpalmatellez que te gusta aprobar PR's?

2021-01-27 12:50 UTC, gmq commented on scripts/santoral.js
> +      if (response.statusCode === 200 || !error) {
No entiendo este if, para propósitos de este GET hay algún caso en que no tire error pero que sea 200?

2021-01-27 14:06 UTC, lgaticaq commented on scripts/santoral.js
> +      if (response.statusCode === 200 || !error) {
Creo que la idea es ejecutar la lógica solo cuando no exista el error. Técnicamente esta debe ejecutarse solo si no existe error y que el status code sea uno valido, en este caso 200. Quizás tenga mas sentido algo como.
`if (!error && response.statusCode === 200)`

2021-01-27 16:05 UTC, juanbrujo commented
:pray: @gmq

2021-01-27 16:08 UTC, gmq approved these changes

2021-01-27 16:10 UTC, merged