Script que pide definción de palabra desde la RAE
devschile/huemul pull request #662
Opened 2021-04-13 23:06 UTC by fskarmeta

## Descripción
La RAE no tiene API oficial para solicitar la definición de una palabra, tampóco encontré alguna otra API que haga esto.
Este script usa la URL pública para buscar una palabra en su página `https://dle.rae.es/srv/search?w=palabra` y con la ayuda de cheerio extrae el contenido de la defincion de un meta tag del html.

Cuando no se ha encontrado palabra el mismo web scrap devuelve siempre el mismo contenido:
`Versión electrónica 23.4 del «Diccionario de la lengua española», obra lexicográfica académica por excelencia.`
Por lo que usé la primera palabra `Versión` como indicador para una palabra no existente o incorrecta.

Se uso node-fetch en vez del robot http request. Si esto es problemático puedo intentar cambiarlo.

## Ejemplo de comportamiento

Comandos: define|rae

@Huemul define extravagante
`1. adj. Que se hace o dice fuera del orden o común modo de obrar. 2. adj. Raro, extraño, desacostumbrado, excesivamente peculiar u original.`

@Huemul rae entusiasmo
`1. m. Exaltación y fogosidad del ánimo, excitado por algo que lo admire o cautive. 2. m. Adhesión fervorosa que mueve a favorecer una causa o empeño.`

@Huemul define asdadasd
`No se encontró aquella palabra :sadhuemul:`

2021-04-13 23:17 UTC, juanbrujo commented on scripts/rae.js
> +    }).catch(e => msg.send("Ohh no, algo no esta funcionando bien. ¿Conocen algun programador que pueda ver esto? :kappa:"))
typo: `está`

2021-04-13 23:18 UTC, juanbrujo commented on scripts/rae.js
> +    }).catch(e => msg.send("Ohh no, algo no esta funcionando bien. ¿Conocen algun programador que pueda ver esto? :kappa:"))
`algún`

2021-04-13 23:20 UTC, juanbrujo approved these changes

2021-04-13 23:35 UTC, lgaticaq requested changes

2021-04-13 23:35 UTC, lgaticaq commented on scripts/rae.js
> +        if (definition.split(" ")[0] == "Versión") {
Es posible que esto de error? Además usar el `===` 🙏

2021-04-14 01:16 UTC, fskarmeta commented on scripts/rae.js
> +    }).catch(e => msg.send("Ohh no, algo no esta funcionando bien. ¿Conocen algun programador que pueda ver esto? :kappa:"))
Typos arreglados.
Concluí que dado que las palabras compuestas se pueden escribir juntas, de detectar dos palabras, las juntará e intentará encontrar un match.
Cuéntame qué te parece.

2021-04-14 01:20 UTC, fskarmeta commented on scripts/rae.js
> +        if (definition.split(" ")[0] == "Versión") {
He testeado bastante y no me ha dado ningún error.  Claro que si llega a cambia la fuente original eventualmente podrá dar error pero ahí estaré presente para remediarlo de pasar eso :o. De todos modos veo difícil que eso suceda en el corto o mediano plazo. Se agregó igualdad estricta. Quedo atento!

2021-04-14 01:31 UTC, juanbrujo commented on scripts/rae.js
> +
2 line-breaks, puede ser solo 1 porfa?

2021-04-14 01:32 UTC, juanbrujo commented on scripts/rae.js
> +    }
este if puede estar en 1 linea:

`if (msg.match[3]) word += msg.match[3].trim()`

2021-04-14 01:33 UTC, juanbrujo commented on scripts/rae.js
> +    let word = msg.match[2].trim()
creo que este puede ser un const

2021-04-14 01:34 UTC, juanbrujo commented on scripts/rae.js
>          msg.send(definition)
tab plz

2021-04-14 01:34 UTC, juanbrujo approved these changes
pequeños detalles pero por mi va

2021-04-14 01:38 UTC, dukuo commented on scripts/rae.js
> +    }).catch(e => msg.send("Ohh no, algo no está funcionando bien. ¿Conocen algún programador que pueda ver esto? :kappa:"))
En honor a devsChile se podría usar :huemul-patitas:

2021-04-14 01:49 UTC, fskarmeta commented on scripts/rae.js
> +    }
ok, y este ? 
`const word = msg.match[3] ? msg.match[2].trim() + msg.match[3].trim() : msg.match[2].trim()`

2021-04-14 01:55 UTC, fskarmeta commented on scripts/rae.js
> +    }).catch(e => msg.send("Ohh no, algo no está funcionando bien. ¿Conocen algún programador que pueda ver esto? :kappa:"))
done :d

2021-04-14 02:00 UTC, dukuo approved these changes

2021-04-14 02:13 UTC, juanbrujo commented on scripts/rae.js
> +        if (definition.split(" ")[0] == "Versión") {
falta resolver esto para el 🆗 de Leo

2021-04-14 17:45 UTC, lgaticaq commented on scripts/rae.js
> +        if (definition.split(" ")[0] === "Versión") {
Solo para evitar errores futuros en caso de que cambie la estructura de la pagina verificaría antes de acceder a la posición 0 del array si este tiene elementos. El resto lo veo 👌.

2021-04-14 17:46 UTC, lgaticaq approved these changes

2021-04-14 17:57 UTC, merged

2021-04-14 17:57 UTC, juanbrujo commented
se fue la shiet